USE alx_book_store;
CREATE TABLE IF NOT EXISTS Books (
	book_id AUTO_ICREMENT PRIMARY KEY
	title VARCHAR(130) NOT NULL
	price DOUBLE NOT NULL
	publication_date DATE
	FOREIGN KEY (author_id) REFERENCES authors(author_id) ON DELETE SET NULL
	)
CREATE TABLE IF NOT EXISTS Authors (
	author_id AUTO_ICREMENT PRIMARY KEY
	author_name VARCHAR(215) NOT NULL
	)
CREATE TABLE IF NOT EXISTS Customers (
	customer_id AUTO_INCREMENT PRIMARY KEY
	customer_name VARCHAR(215) NOT NULL 
	email VARCHAR(215) NOT NULL
	address TEXT 
	)
CREATE TABLE IF NOT EXSTS Orders (
	order_id INT  AUTO_INCREMENT PRIMARY KEY
	FOREIGN KEY (customer_id) REFERENCES Customers(customer_id) ON DELETE SET CASCADE
        order_date DATE
	customer_id INT
CREATE TABLE IF NOT EXISTS Order_Details (
	orderdetail_id AUTO_INCREMENT PRIMARY KEY
	FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE SET CASCADE
	FOREIGN KEY (book_id) REFERENCES Books(book_id) ON DELETE SET CASCADE
	quantity DOUBLE NOT NULL 
	)
